# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: build-docs

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout and setup
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: install and build
      run: | 
        npm install -D vuepress
        java -jar ./node-1.0-SNAPSHOT-jar-with-dependencies.jar
        npm run docs:build

    - name: commit
      run: |
        cd ./dist
        echo 'tiankafei.top' > CNAME
        git config --global user.email "weishuangshuang89@163.com"
        git config --global user.name "tiankafei"
        git init
        git add -A
        git commit -m '提交部署文件'
        git push -f git@github.com:tiankafei/tiankafei.git master

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
